### ISSUE TITLE
Not Compatible With spring-integration 4.0

### ISSUE THREAD

**Issue by watchwithmike** [spring-projects/spring-integration-dsl-groovy#13]
It looks like some classes originally in org.springframework.integration have been moved to the spring-messaging project, most notably the Message class:

```
org/springframework/integration/Message
java.lang.NoClassDefFoundError: org/springframework/integration/Message
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1336)
	at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1197)
	at java.beans.Introspector.getBeanInfo(Introspector.java:426)
	at java.beans.Introspector.getBeanInfo(Introspector.java:173)
	at org.springframework.integration.dsl.groovy.builder.IntegrationBuilder.<init>(IntegrationBuilder.groovy:55)
```

**Comment by garyrussell** [comment]
The latest [commit on master](https://github.com/spring-projects/spring-integration-dsl-groovy/commit/836d37b039cde3a8d8e066575ac8941289c891b5) updated to SI 4.x.

What version are you using? You should be ok if you build from master.

As you can see this project has not had much activity; it never gained much traction with the community; we have seen much higher uptake with the [Java DSL](https://github.com/spring-projects/spring-integration-java-dsl) - especially when used with Java 8 and lambdas.

That said, if there are problems here, we will strive to correct them as time permits.

**Comment by watchwithmike** [comment]
Thank you for the prompt response.  I was using 1.0.0M1 and not Master.  Sounds like it's time to study up on Java 8 lambdas.

**Comment by garyrussell** [comment]
I just issued a PR to bring it up to SI 4.1... https://github.com/spring-projects/spring-integration-dsl-groovy/pull/14
