### ISSUE TITLE
Error running  a Spring Integration using spring boot/groovy dsl

### ISSUE THREAD

**Issue by ledzepu2** [spring-projects/spring-integration-dsl-groovy#6]
I have created a Spring Boot project where i included Spring Integration starter/Spring Integration dsl groovy/dsl-groovy http. 

This is the snippet from my build.gradle
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'spring-boot'
apply plugin: 'groovy'
apply plugin: 'war'
apply plugin: 'jetty'
apply plugin: 'application'

mainClassName = 'hello.Application'

war {
    baseName = 'gs-integration'
    version =  '0.1.0'
}

repositories {
    mavenCentral()
    maven { url "http://repo.spring.io/libs-snapshot" }
}

dependencies {
    compile('org.springframework.boot:spring-boot-starter-web:1.0.0.RC5') {
        exclude group:'org.springframework.boot', module:'spring-boot-starter-tomcat'
    }
    compile 'org.springframework.boot:spring-boot-starter-actuator:1.0.0.RC5'
    compile 'org.springframework.boot:spring-boot-starter-jetty:1.0.0.RC5'
    compile 'org.springframework:spring-context-support:4.0.0.M3'
    compile("org.codehaus.groovy:groovy-all:2.1.6")
    compile("org.springframework.boot:spring-boot-starter-integration")
    compile("org.springframework.integration:spring-integration-dsl-groovy-core:1.0.0.M1")
    {
    exclude group:'org.springframework.integration', module:'spring-integration-http'
        }
    compile("org.springframework.integration:spring-integration-dsl-groovy-http:1.0.0.M1")
    testCompile("junit:junit-dep:4.8.2")
}
When i do gradle clean run, i am getting a stacktrace 
Caused by: java.lang.ClassNotFoundException: org.springframework.integration.http.inbound.UriPathHandlerMapping
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at org.springframework.util.ClassUtils.forName(ClassUtils.java:236)
    at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:392)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1348)
    at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1319)
    ... 94 more
This is my dsl which i have used 
doWithSpringIntegration {
    namespaces('int-http')
    springXml {
        bean(id:'uriPathHandlerMapping','class':'org.springframework.integration.http.inbound.UriPathHandlerMapping')

```
    'int-http:inbound-gateway'(id:'events-inbound-gateway',
    'request-channel':'events-request-inbound-channel',
    'reply-channel':'events-response-inbound-channel',
    'path':'/examples/eventsFlow',
    'supported-methods':'GET'
    )

    'si:channel'(id:'events-request-inbound-channel')
    'si:channel'(id:'events-response-inbound-channel')
}

flow = messageFlow{
    httpGet(url:{"http://www.google.com/finance/info?q=$it"},responseType:String,requestChannel:'events-request-inbound-channel')
```

//      httpGet(responseType:String,requestChannel:'events-request-inbound-channel')
    }
}

**Comment by razazaran** [comment]
I have a question here. I am trying to access spring configuration file using junit, but it is failing before setUp() method with following errror:
10:33:21.494 INFO  [main][org.springframework.integration.http.inbound.IntegrationRequestMappingHandlerMapping] Mapped "{[/getBillServiceImplReq],methods=[POST],params=[],headers=[],consumes=[],produces=[],custom=[]}" 
onto public abstract void org.springframework.web.HttpRequestHandler.handleRequest(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws javax.servlet.ServletException,java.io.IOException

**Comment by razazaran** [comment]
here is my Junit:
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath:/WEB-INF/upperSI/http/servlet-config.xml" })
@WebAppConfiguration
public class RestGetServiceImplTest{
	@Autowired
    private WebApplicationContext webApplicationContext; 		
	private MockMvc mockMvc;
	
	/**
	 * Set variables and Objects which are need to execute the test-case.
	 * @throws IOException 
	 */
	@Before
	public void setUp() throws Exception{
		this.mockMvc = MockMvcBuilders.webAppContextSetup(this.webApplicationContext).build();
			}
	.......................................

**Comment by razazaran** [comment]
and servlet-config code im trying to access/load is :
<int-http:inbound-gateway request-channel="getBillServiceImplChannel"
		supported-methods="POST" path="/getBillServiceImplReq" mapped-request-headers="HttpHeaders.REQUEST_URL"/>
		
	
	<int:header-enricher input-channel="getBillServiceImplChannel"
		output-channel="getBillServiceReqJsonImplChannel">
		<int:header name="content-type" value="application/json"></int:header>
	</int:header-enricher>

	<int:chain input-channel="getBillServiceReqJsonImplChannel">
	
	<int:json-to-object-transformer type="com.nbad.echannel.common.model.GetBillType" object-mapper="jackson2JsonObjectMapper" />
	 
	<int:service-activator>
		<bean class="com.nbad.echannel.service.account.impl.GetBillServiceImpl"><constructor-arg ref="getDepositType"></constructor-arg></bean>
	</int:service-activator>	
 
	<int:object-to-json-transformer content-type="application/json" />
	</int:chain>
